name: release
on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - 'releases/**'
      - 'ci/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, cloud3b]
    steps:
      - name: CI
        uses: agilesyndrome/github-actions@21da51286b7097127e7fadd5012d98aad0f75aa0

        with:
          makefile_target: ci

