name: release
on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - 'releases/**'
      - 'ci/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, cloud3b]
    steps:
      - name: CI
        uses: agilesyndrome/github-actions@daaf09a8b4d1bb35ee6073bf93914d8bf72c74ae


        with:
          makefile_target: ci

