name: release
on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - 'releases/**'
      - 'ci/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: CI
        uses: agilesyndrome/github-actions@main
        with:
          makefile_target: ci
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PASSPHRASE }}