name: release
on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - 'releases/**'
      - 'ci/**'
jobs:
  ci:
    #runs-on: ubuntu-latest
    runs-on: cloud-3b
    steps:
      - name: CI
        uses: agilesyndrome/github-actions@fixup-ci
        with:
          makefile_target: ci

