name: release
on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - master
      - 'releases/**'
      - 'ci/**'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: CI
        uses: agilesyndrome/github-actions
        makefile_target: ci

