name: Test
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Setup variables
        id: setupenv
        run: make setupenv >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.setupenv.outputs.GO_VERSION }}
      - name: Build and Test
        run: make ci
